name: cometchat_chat_uikit_example
description: A minimal example app demonstrating the CometChat Flutter UI Kit.
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  cometchat_chat_uikit:
    path: ../

flutter:
  uses-material-design: true
