import '../../../cometchat_uikit_shared.dart';

/// Represents a stream message in the chat.
///
/// This class extends [AIAssistantMessage] and initializes
/// with predefined [type] = "run_started" and [category] = "custom".
class StreamMessage extends AIAssistantMessage {
  /// Constructs a new [StreamMessage].
  StreamMessage({
    int? runId,
    String? threadId,
    required String text,
    List<String>? tags,
    int id = 0,
    String muid = '',
    User? sender,
    AppEntity? receiver,
    required String receiverUid,
    required String receiverType,
    DateTime? sentAt,
    DateTime? deliveredAt,
    DateTime? readAt,
    Map<String, dynamic>? metadata,
    DateTime? readByMeAt,
    DateTime? deliveredToMeAt,
    DateTime? deletedAt,
    DateTime? editedAt,
    String? deletedBy,
    String? editedBy,
    DateTime? updatedAt,
    String? conversationId,
    int parentMessageId = 0,
  }) : super(
    runId: runId,
    threadId: threadId,
    text: text,
    tags: tags,
    id: id,
    muid: muid,
    sender: sender,
    receiver: receiver,
    receiverUid: receiverUid,
    receiverType: receiverType,
    type: CometChatMessageType.runStarted,
    category: CometChatMessageCategory.streamMessage,
    sentAt: sentAt,
    deliveredAt: deliveredAt,
    readAt: readAt,
    metadata: metadata,
    readByMeAt: readByMeAt,
    deliveredToMeAt: deliveredToMeAt,
    deletedAt: deletedAt,
    editedAt: editedAt,
    deletedBy: deletedBy,
    editedBy: editedBy,
    updatedAt: updatedAt,
    conversationId: conversationId,
    parentMessageId: parentMessageId,
  );

  /// ✅ CopyWith method for updating fields while keeping others unchanged
  StreamMessage copyWith({
    int? runId,
    String? threadId,
    String? text,
    List<String>? tags,
    int? id,
    String? muid,
    User? sender,
    AppEntity? receiver,
    String? receiverUid,
    String? receiverType,
    DateTime? sentAt,
    DateTime? deliveredAt,
    DateTime? readAt,
    Map<String, dynamic>? metadata,
    DateTime? readByMeAt,
    DateTime? deliveredToMeAt,
    DateTime? deletedAt,
    DateTime? editedAt,
    String? deletedBy,
    String? editedBy,
    DateTime? updatedAt,
    String? conversationId,
    int? parentMessageId,
  }) {
    return StreamMessage(
      runId: runId ?? this.runId,
      threadId: threadId ?? this.threadId,
      text: text ?? this.text ?? "",
      tags: tags ?? this.tags,
      id: id ?? this.id,
      muid: muid ?? this.muid,
      sender: sender ?? this.sender,
      receiver: receiver ?? this.receiver,
      receiverUid: receiverUid ?? this.receiverUid,
      receiverType: receiverType ?? this.receiverType,
      sentAt: sentAt ?? this.sentAt,
      deliveredAt: deliveredAt ?? this.deliveredAt,
      readAt: readAt ?? this.readAt,
      metadata: metadata ?? this.metadata,
      readByMeAt: readByMeAt ?? this.readByMeAt,
      deliveredToMeAt: deliveredToMeAt ?? this.deliveredToMeAt,
      deletedAt: deletedAt ?? this.deletedAt,
      editedAt: editedAt ?? this.editedAt,
      deletedBy: deletedBy ?? this.deletedBy,
      editedBy: editedBy ?? this.editedBy,
      updatedAt: updatedAt ?? this.updatedAt,
      conversationId: conversationId ?? this.conversationId,
      parentMessageId: parentMessageId ?? this.parentMessageId,
    );
  }
}
