name: sample_app
description: "A sample app"
publish_to: 'none'
version: 6.1.1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cometchat_chat_uikit: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  http: ^1.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/
